[Unit]
After=local-fs.target

[Service]
Environment="client_opt5=--auth-user-pass /tmp/vpn-ramdisk/userpassword.txt --askpass /tmp/vpn-ramdisk/key-pass.txt"

ExecStartPre=/usr/bin/env DISPLAY=:0 xterm -T "VPN" -e "/rw/config/prepare-vpn-usb.sh"

TimeoutStartSec=10m
